#!/bin/bash

set -u
set -e

ADDRESS="http://localhost:8000"

mkdir -p cache ui tmp

call_curl() {
  want=$1
  shift
  echo "CALL $*"
  echo -n "  WANT ${want}..."
  ret="$(curl -s --write-out "%{http_code}" --output /dev/null -X "$@")"
  echo "GOT $ret"
  test "$ret" == "$want"
}

call_curl 200 GET $ADDRESS
call_curl 200 GET $ADDRESS/ui/
call_curl 201 PUT -d 123 http://localhost:8000/api/3c9909afec25354d551dae21590bb26e38d53f2173b8d3dc3eee4c047e7ab1c1eb8b85103e3be7ba613b31bb5c9c36214dc9f14a42fd7a2fdb84856bca5c44c2/
